# Numpy 2.2 - Array Attribute & Basic operations

This notebook covers:

- Array attributes: ndim, shape, size, dtype
- Reshaping arrays
- Indexing & Slicing
- Element-wise mathematical operations
- Broadcasting rules
- Aggregation functions: sum, mean, std, min, max, argmin, argmax

Includes **examples**, **exercises**, and **solutions** for practice.

In [1]:
import numpy as np

In [3]:
# crate 1D and 2D array
a1 = np.array([10, 20, 30, 40, 50])
a2 = np.array([[1, 2, 3], [4, 5, 6]])

print("a1:", a1)
print("ndim:", a1.ndim) # ndim is number of dimensions
print("shape:", a1.shape) # shape is number of rows and columns
print("size:", a1.size) # size is total number of elements
print("dtype:", a1.dtype) # dtype is data type

print("a2:", a2)
print("ndim:", a2.ndim) # ndim is number of dimensions
print("shape:", a2.shape)
print("size:", a2.size)
print("dtype:", a2.dtype)

a1: [10 20 30 40 50]
ndim: 1
shape: (5,)
size: 5
dtype: int64
a2: [[1 2 3]
 [4 5 6]]
ndim: 2
shape: (2, 3)
size: 6
dtype: int64


**Exersize 1 --  Array Attribute**

crate a 3*4 array using `np.arange()` and reshape it. Then print `ndim`, `shape`, `size`, and `dtype` (Try `dtype=float`)

In [6]:
# exersize 1 
# your code

arr = np.arange(0, 12)
print(arr)

arr = arr.reshape(3, 4)
print(arr)

print("ARR:", arr)
print("ndim:", arr.ndim) # ndim is number of dimensions
print("shape:", arr.shape)
print("size:", arr.size)
print("dtype:", arr.dtype)



[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
ARR: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
ndim: 2
shape: (3, 4)
size: 12
dtype: int64
