In [ ]:
# basic (normal) python code

prices = [100, 200, 300, 400, 500]
new_price = []

for price in prices:
    new_price.append(price * 1.10)

for x in new_price:
    print(f"{x:.2f}")

110.00
220.00
330.00
440.00
550.00


In [1]:
import numpy as np

In [ ]:
# using numpy

price = np.array([100, 200, 300, 400, 500])
new_price = price * 1.10
print(new_price)

[110. 220. 330. 440. 550.]


In [3]:
# mathematical operation

a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
print(a,b)
print(a+b)
print(np.add(a,b))

[10 20 30 40] [1 2 3 4]
[11 22 33 44]
[11 22 33 44]


In [11]:
# mathematical operation

a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
print(a,b)
print(a-b)
print(np.subtract(a,b))

[10 20 30 40] [1 2 3 4]
[ 9 18 27 36]
[ 9 18 27 36]


In [12]:
# mathematical operation

a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
print(a,b)
print(a*b)
print(np.multiply(a,b))

[10 20 30 40] [1 2 3 4]
[ 10  40  90 160]
[ 10  40  90 160]


In [13]:
# mathematical operation

a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
print(a,b)
print(a/b)
print(np.divide(a,b))

[10 20 30 40] [1 2 3 4]
[10. 10. 10. 10.]
[10. 10. 10. 10.]


In [14]:
a = np.array([10,20,30,40])
print(a/3)

[ 3.33333333  6.66666667 10.         13.33333333]


In [19]:
a = np.array([10,20,30,40])
# print(a ** 3)  # power  OR 
print(np.power(a,3))

[ 1000  8000 27000 64000]


In [16]:
a = np.array([10,20,30,40])
print(a%3)

[1 2 0 1]


In [17]:
a = np.array([10,20,30,40])
print(a//3)

[ 3  6 10 13]


In [ ]:
# mathematical operation in normal python

a = [10,20,30,40]
b = [1,2,3,4]
c = []
if(len(a)==len(b)):
    #pass
    for x in range(len(a)):
        c.append(a[x] + b[x]) # append means to add at the end
else:
    print("Length both lists doesn't match!")
print (c)

[11, 22, 33, 44]


In [18]:
# mathematical operation in normal python

a = [10,20,30,40]
b = [1,2,3,4]
c = []
if(len(a)==len(b)):
    #pass
    for x in range(len(a)):
        c.append(a[x] + b[x]) # append means to add at the end
# elif (len(a) != len(b)):
#     for x in range(len(a)):
#         c.append(a[x] + b[x])

else:
    print("Length both lists doesn't match!")
print (c)

[11, 22, 33, 44]


In [20]:
numbers = np.array ([4,9,16,25])
newnum = np.sqrt(numbers)
print(newnum)

[2. 3. 4. 5.]


In [21]:
numbers = np.array ([-118, 55,-0,43,-33,75])
newnum = np.abs(numbers)
print(newnum)

[118  55   0  43  33  75]


# Exponential

In [22]:
print(np.exp(1))

2.718281828459045


In [23]:
print(np.exp(2))

7.38905609893065


# Round of Nums

In [35]:
numbers = np.array ([10.42424, 20.4422, 30.99])
print(np.round(numbers,2))

[10.42 20.44 30.99]


In [33]:
numbers = np.array ([10.42424, 20.4422, 30.9999])
print(np.floor(numbers))

[10. 20. 30.]


In [34]:
numbers = np.array ([10.42424, 20.4422, 30.6333])
print(np.ceil(numbers))

[11. 21. 31.]


# Aggregate Functions

In [36]:
nums = [75,88,43,6,72]
print(np.sum(nums))

284


In [37]:
print(np.mean(nums))

56.8


In [38]:
print(np.median(nums))

72.0


In [39]:
print(np.min(nums))

6


In [40]:
print(np.max(nums))

88


In [42]:
print(np.argmax(nums))  # gives the index number of the maximum value (start from 0)

1


In [43]:
print(np.argmin(nums))  # gives the index number of the minimum value (start from 0)

3


In [44]:
print(np.var(nums)) # var is the variance

861.36


In [45]:
print(np.std(nums)) # std is the standard deviation

29.348935244740993


In [1]:
import numpy as np
marks = np.array([
    [80, 90, 70],
    [60, 75, 85],
    [90, 95, 88]
    ])
print(np.sum(marks, axis =0 )) # column wise
print(np.sum(marks, axis =1 )) # row wise

[230 260 243]
[240 220 273]


In [3]:
print(np.mean(marks, axis =0 ))
print(np.mean(marks, axis =1 ))

[76.66666667 86.66666667 81.        ]
[80.         73.33333333 91.        ]


In [10]:
print(np.min(marks, axis =0 ))
print(np.max(marks, axis =0 ))

[60 75 70]
[90 95 88]


In [6]:
print(np.median(marks, axis =0 ))

[80. 90. 85.]


# Comparison Operator


In [ ]:
marks = np.array([45, 67, 89, 32, 76])
print(marks)
print(marks > 50)
print(marks < 50)
print(marks >= 60)
print(marks <= 70)
print(marks == 89)
print(marks != 76)


[45 67 89 32 76]
[False  True  True False  True]
[ True False False  True False]
[False  True  True False  True]
[ True  True False  True False]
[False False  True False False]
[ True  True  True  True False]


In [10]:
# WAP to add all the elements of array1 which are equal to all above 60 into array2

array1 = np.array([10,20,30,40,50,60,70,80,90,100])
array2 = np.array([1,2,3,4,5,6,7,8,9,10])
print(array1[array1>60])
print(array2[array1>60])


[ 70  80  90 100]
[ 7  8  9 10]


In [15]:
# WAP to add all the elements of array1 which are equal to all above 60 into array2 using normal python code

marks = np.array([45, 67, 89, 32, 76])
li= []
for x in marks:
    if x >= 60:
        li.append(x)
for x in li:
    print(x)


67
89
76


In [16]:
marks = np.array([45,67,89,32,76])
res = marks[marks >= 60]
print(res)

[67 89 76]


In [ ]:
salary = np.array([25000,30000,35000,45000,50000,60000])
great = salary[(salary >= 35000) & (salary <= 50000)]
print(great)

# or other way of writing 
con = np.logical_and(
    salary >= 35000,
    salary <= 50000
)
print(salary[con])

[35000 45000 50000]
[35000 45000 50000]


In [30]:
salary = ([25000,30000,35000,45000,50000,60000])
great = []
for x in salary:
    if 35000 <= x <= 50000:  
        great.append(x)
print(great)

[35000, 45000, 50000]


# 08 09 2026
# logical not

In [3]:
# salary = np.array([25000,30000,35000,45000,50000,60000])

val = np.array([True, False, True, False])
print(val)
print(np.logical_not(val))

[ True False  True False]
[False  True False  True]


# NumPy Array Slicing

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


# Negative Slicing
**Use the minus operator to refer to an index from the end:**

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


# STEP
**Use the step value to determine the step of the slicing:**

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


# Slicing 2-D Arrays
**From the second element, slice elements from index 1 to index 4 (not included):**

In [10]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [14]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


**From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:**

In [19]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# NumPy Data Types

In [21]:
# checking the data types
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [ ]:
# Create an array with data type 4 bytes integer:
arr = np.array([1, 2, 3, 4], dtype='i4')  # i4 means 4 bytes integer
# 'i4' can be changed randomly by requirement 

print(arr)
print(arr.dtype)


[1 2 3 4]
int32


**Converting Data Type on Existing Arrays**

In [25]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)


[1 2 3]
int32


# NumPy Array Copy vs View

In [ ]:
# COPY
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()  # the changes in x will not reflect in arr
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
# VIEW:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view() # the changes in x will reflect in arr 
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


# Check if Array Owns its Data
**As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.**

In [30]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)
# The copy returns None.
# The view returns the original array.

None
[1 2 3 4 5]


# NumPy Array Shape
**Shape of an Array**


In [3]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [4]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# NumPy Array Reshaping
Reshape From 1-D to 2-D

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Reshape From 1-D to 3-D

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2) # 2 means dimension, 3 means 3 one dimensional array, 2 means column or element

print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

# Returns Copy or View?

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


# Unknown Dimension

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Flattening the arrays

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


# NumPy Array Iterating

In [14]:
# Iterating Arrays
arr = np.array([1, 2, 3])

for x in arr:
  print(x)


1
2
3


In [15]:
# Iterating 2-D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [17]:
# Iterating 3-D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [18]:
# To return the actual values, the scalars, we have to iterate the arrays in each dimension.
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [19]:
# Iterating Arrays Using nditer()
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)


1
2
3
4
5
6
7
8


# Iterating Array With Different Data Types

In [2]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)


np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


# Iterating With Different Step Size

In [7]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


# Enumerated Iteration Using ndenumerate()

In [4]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [5]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# NumPy Joining Array
**Joining NumPy Arrays**

In [8]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
# Join two 2-D arrays along rows (axis=1):

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1) # concatenate means join

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


# Joining Arrays Using Stack Functions

In [13]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1) # axis can be changed 0 or 1 0=row, 1=column  # stack means join

print(arr)

[[1 4]
 [2 5]
 [3 6]]


# Stacking Along Rows
**NumPy provides a helper function: hstack() to stack along rows.**

In [15]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))  # hstack means horizontal stack

print(arr)

[1 2 3 4 5 6]


# Stacking Along Columns
**NumPy provides a helper function: vstack()  to stack along columns.**

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2)) # vstack means vertical stack

print(arr)

[[1 2 3]
 [4 5 6]]


# Stacking Along Height (depth)
**NumPy provides a helper function: dstack() to stack along height, which is the same as depth.**

In [17]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# NumPy Splitting Array
**Splitting NumPy Arrays**

In [19]:
# Split the array in 3 parts:

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [20]:
# Split the array in 4 parts:


arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# Split Into Arrays

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


# Splitting 2-D Arrays

In [22]:
# Split the 2-D array into three 2-D arrays.


arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [23]:
# Split the 2-D array into three 2-D arrays.


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [24]:
# Split the 2-D array into three 2-D arrays along columns.


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


**An alternate solution is using hsplit() opposite of hstack()**

In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# NumPy Searching Arrays
You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)  # it gives index number where values is 4

print(x)

(array([3, 5, 6]),)


In [28]:
# Find the indexes where the values are odd:


arr = np.array([10, 14, 93, 41, 8, 7])

x = np.where(arr%2 == 1)

print(x)

(array([2, 3, 5]),)


In [29]:
arr = np.array([10, 14, 93, 41, 8, 7])

x = np.where(arr%2 == 0)

print(x)

(array([0, 1, 4]),)


# Search Sorted
**The searchsorted() method is assumed to be used on sorted arrays.**


In [30]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [31]:
# Search From the Right Side
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [32]:
# Multiple Values:
# Find the indexes where the values 2, 4, and 6 should be inserted:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


# NumPy Sorting Arrays
**Sorting Arrays**

In [33]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))


[0 1 2 3]


In [34]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [35]:
# Sort a boolean array:


arr = np.array([True, False, True])  # false means 0 and true means 1

print(np.sort(arr))

[False  True  True]


# Sorting a 2-D Array
**If you use the sort() method on a 2-D array, both arrays will be sorted:**

In [36]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [40]:
# descending 
arr=np.array([3,1,9,5,2])

sorted_arr=np.sort(arr,descending=False)

print(sorted_arr)

[1 2 3 5 9]


# NumPy Filter Array


In [41]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


# Creating the Filter Array

In [42]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [43]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


# Creating Filter Directly From Array


In [44]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False  True False  True False  True False]
[2 4 6]


# Arange (array range)

In [ ]:
import numpy as np

In [2]:
arr = np.array([0,1,2,3,4])
print(arr)

newarr = np.arange(5) # take a range and convert it into array
print(newarr)

[0 1 2 3 4]
[0 1 2 3 4]


In [3]:
# numbers from 0 to 9
seq1 = np.arange(10) 

# numbers from 2 to 10 skipping by 2
seq2 = np.arange(2, 11, 2)

# np.linspace()
linear space

In [4]:
linear_space = np.linspace(0, 10, 5) # linear space from 0 to 10 with 5 elements
print(linear_space)

[ 0.   2.5  5.   7.5 10. ]


In [5]:
linear_space = np.linspace(0, 33, num=5)
print(linear_space)

[ 0.    8.25 16.5  24.75 33.  ]


# Zeros And Ones

In [6]:
zeros_arr = np.zeros((2, 3))
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
ones_arr = np.ones(3)
ones_arr = np.ones((2, 3))
print(ones_arr)


[[1. 1. 1.]
 [1. 1. 1.]]


# full (np.full)

In [8]:
full_arr = np.full ((2,2),7)
print(full_arr)

[[7 7]
 [7 7]]


# Identity Matrix (eye)

In [9]:
# A 3*3 identity matrix

identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# NumPy Array Broadcasting
(https://www.geeksforgeeks.org/numpy/numpy-array-broadcasting/)

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]])
x = 10
print(a + x)

[[11 12 13]
 [14 15 16]]


Broadcasting a Scalar to a 1D Array

In [11]:
arr = np.array([1, 2, 3])
res = arr + 1  
print(res)

[2 3 4]


Broadcasting a 1D Array to a 2D Array

In [12]:
a = np.array([2, 4, 6])
b = np.array([[1, 3, 5], [7, 9, 11]])
res = a + b
print(res)

[[ 3  7 11]
 [ 9 13 17]]


In [13]:
a = np.array([12, 24, 35, 45, 60, 72])
b = np.array(["Adult", "Minor"])
res = np.where(a > 18, b[0], b[1])
print(res)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']


Using Broadcasting for Matrix Multiplication

In [14]:
m = np.array([[1, 2], [3, 4]])
v = np.array([10, 20])
res = m * v
print(res)

[[10 40]
 [30 80]]


In [15]:
fd = np.array([ [0.8, 2.9, 3.9],
                [52.4, 23.6, 36.5],
                [55.2, 31.7, 23.9],
                [14.4, 11.0, 4.9] ])

cpg = np.array([9, 4, 4])
res = fd * cpg
print(res)

[[  7.2  11.6  15.6]
 [471.6  94.4 146. ]
 [496.8 126.8  95.6]
 [129.6  44.   19.6]]
