# NumPy 2.1 - Introduction to Numpy
**Beginner to Intermediate Levels**

This notebook covers the foundational concepts of Numpy, including:
- Importing Numpy
- Numpy Arrays vs Python Lists
- Creating Arrays using `arrays`, `arange`, `linspace`, `zeros`, `ones`, `empty`, `eye`
- Examples, Exercises, and Solutions

In [3]:
import numpy as np
# check version
print("NumPy Version:",np.__version__) 

NumPy Version: 2.5.2


In [4]:
# Numpy Array Example 
my_array = np.array([1,2,3,4])
print("Numpy Array:", my_array, "| Type:", type(my_array))

# Vectorized addition (no loop required)
array_result = my_array + 5
print("After Adding 5:", array_result)

Numpy Array: [1 2 3 4] | Type: <class 'numpy.ndarray'>
After Adding 5: [6 7 8 9]


In [5]:
# speed comparison
import time

size = 10_000_000
# same as size = 10000000 10 milliom elements

# Python List
list1 = list(range(size))
start = time.time()
list2 = [x*2 for x in list1]
print("Python List Time:", round(time.time() - start, 4), "sec")

# Numpy Array
array1 = np.arange(size)
start = time.time()
array2 = array1 * 2
print("Numpy Array Time:", round(time.time() - start, 4), "sec")

Python List Time: 6.3301 sec
Numpy Array Time: 0.4117 sec


## 3️⃣ Creating Arrays
NumPy provides multiple ways to create arrays:
- `np.array(): This is the most fundamental way to create an array. It converts a Python list, tuple, or other array-like object into a NumPy array.`
```
    import numpy as np
    my_list = [1, 2, 3, 4, 5]
    numpy_array = np.array(my_list)
    print(numpy_array)
```
- `np.arange(): This function creates an array with evenly spaced values within a given range, similar to Python's built-in range() function but returning a NumPy array. You can specify a start, stop, and step size.`
```
    import numpy as np
    arr_range = np.arange(0, 10, 2) # Array from 0 (inclusive) to 10 (exclusive), with a step of 2
    print(arr_range)
```
- `np.linspace(): This function generates an array with a specified number of evenly spaced values over a specified interval. You provide the start, stop, and the desired number of elements. `
```
    import numpy as np
    arr_linspace = np.linspace(0, 10, 5) # 5 evenly spaced values between 0 and 10 (inclusive)
    print(arr_linspace)
```
- `np.zeros(): This function creates an array of a given shape and data type, filled with zeros.`
```
    import numpy as np
    zeros_array = np.zeros((2, 3)) # A 2x3 array filled with zeros
    print(zeros_array)
```
- `np.ones(): Similar to np.zeros(), this function creates an array of a given shape and data type, filled with ones.`
```
    import numpy as np
    ones_array = np.ones((3, 2)) # A 3x2 array filled with ones
    print(ones_array)
```
- `np.eye(): This function creates a 2-D array with ones on the diagonal and zeros elsewhere, also known as an identity matrix. You specify the number of rows and columns (which are typically the same for an identity matrix).`
```
    import numpy as np
    identity_matrix = np.eye(3) # A 3x3 identity matrix
    print(identity_matrix)
```

In [6]:
# 1D Array
a = np.array([1,2,3,4,5])
print(a)

# 2D Array
b = np.array([[1,2,3],[4,5,6]])
print(b)

# Specific dtype
c = np.array([1,2,3], dtype=float)
print(c)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[1. 2. 3.]


**(b) Using `np.arange(start, stop, step)`**

In [7]:
arr1=np.arange(0, 10)
print("arr1:", arr1)

arr2=np.arange(0, 20, 2)
print("arr2:", arr2)

arr3=np.arange(0, 1, 0.1)
print("arr3:", arr3)


arr1: [0 1 2 3 4 5 6 7 8 9]
arr2: [ 0  2  4  6  8 10 12 14 16 18]
arr3: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


**(c) Using `np.linspace(start, stop, num)`**

in this the logic is that you give the start and end num and num decides how many elements you want

In [8]:
lin1 = np.linspace(0, 50, 5)
print("lin1:", lin1)

lin2 = np.linspace(10, 50, 9)
print("lin2:", lin2)


lin1: [ 0.  12.5 25.  37.5 50. ]
lin2: [10. 15. 20. 25. 30. 35. 40. 45. 50.]


**(d) Using `np.zeros(shape)`**

In [9]:
z1 = np.zeros(5) #1D array
print("z1:", z1)

z2 = np.zeros((2,3)) #2D array
print("z2:", z2)

z3 = np.zeros((3,3), dtype=int) #3D array
print("z3:", z3)

z1: [0. 0. 0. 0. 0.]
z2: [[0. 0. 0.]
 [0. 0. 0.]]
z3: [[0 0 0]
 [0 0 0]
 [0 0 0]]


**(e) Using `np.ones(shape)`**

In [10]:
o1 = np.ones(4) #1D array
print("o1:", o1)

o2 = np.ones((3,2)) #3D array
print("o2:", o2)

o3 = np.ones((2,2), dtype=int) #2D array
print("o3:", o3)

o1: [1. 1. 1. 1.]
o2: [[1. 1.]
 [1. 1.]
 [1. 1.]]
o3: [[1 1]
 [1 1]]


**(f) Using `np.eye(N)`** --> identity matrix

In [11]:
I = np.eye(5)
print(I)

I2 = np.identity(3)
print("I2:", I2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
I2: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


EXERCISE 1: Create a 3x3 matrix filled with 7

EXERCISE 2: Create 10 numbers between 50 and 100 equally spaced

EXERCISE 3: Create array [10, 20, 30, 40, 50], add 5 to each element using NumPy

In [18]:
z4 = np.full((3,3), 7, dtype=int) 
print("z4:", z4)

z4: [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
z3=np.zeros((3,3),dtype=int)
array_result=z3 + 7
print("I:",array_result)

In [12]:
lin3 = np.linspace(50, 100, 10)
print("lin3:", lin3)

lin3: [ 50.          55.55555556  61.11111111  66.66666667  72.22222222
  77.77777778  83.33333333  88.88888889  94.44444444 100.        ]


In [14]:
# EXERCISE 3: Create array [10, 20, 30, 40, 50], add 5 to each element using NumPy
arr4 = np.array([10, 20, 30, 40, 50])
arr4 = arr4 + 5
print(arr4)

[15 25 35 45 55]
